FROM jenkins/jenkins:lts

USER root

# Install required tools + Docker CLI
RUN apt-get update && apt-get install -y \
    docker.io \
    git \
    curl \
    jq \
    bc \
    && rm -rf /var/lib/apt/lists/*

# VERY IMPORTANT: allow Jenkins to access Docker
RUN groupadd -f docker && usermod -aG docker jenkins

USER jenkins